# Created with YamlCreate.ps1 v2.5.0 $debug=QUSU.CRLF.7-6-0-preview5-3.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.defaultLocale.1.10.0.schema.json

PackageIdentifier: CakeWallet.CakeWallet
PackageVersion: 5.4.2
PackageLocale: en-US
Publisher: Cake Labs LLC
PublisherUrl: https://cakewallet.com/
PublisherSupportUrl: https://github.com/cake-tech/cake_wallet/issues
PrivacyUrl: https://cakewallet.com/privacy/
Author: Cake Labs LLC
PackageName: Cake Wallet
PackageUrl: https://github.com/cake-tech/cake_wallet
License: MIT
LicenseUrl: https://raw.githubusercontent.com/cake-tech/cake_wallet/refs/tags/v5.2.0/LICENSE.md
Copyright: Copyright (c) 2018-2025 Cake Labs LLC
# CopyrightUrl:
ShortDescription: Cake Wallet is an open-source, non-custodial, and private multi-currency crypto wallet for Android, iOS, macOS, and Linux.
Description: 'Cake Wallet is an open-source, non-custodial, and private multi-currency crypto wallet for Android, iOS, macOS, and Linux. Cake Wallet includes support for several cryptocurrencies, including: Monero (XMR), Bitcoin (BTC), Ethereum (ETH), Litecoin (LTC), Bitcoin Cash (BCH), Polygon (POL), Solana (SOL), Tron (TRX), Nano (XNO), Zano (ZANO), Decred (DCR), Wownero (WOW).'
Moniker: cake-wallet
Tags:
- bitcoin
- crypto
- cryptocurrency
- ethereum
- exchange
- litecoin
- monero
- multi-currency
- non-custodial
- open-source
- self-custodial
- self-custody
- solana
- store
- swap
- wallet
# ReleaseNotes:
# ReleaseNotesUrl:
# PurchaseUrl:
# InstallationNotes:
# Documentations:
ManifestType: defaultLocale
ManifestVersion: 1.10.0
