# Created with YamlCreate.ps1 v2.5.0 $debug=QUSU.CRLF.7-6-0-preview5-3.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.version.1.10.0.schema.json

PackageIdentifier: CakeWallet.CakeWallet
PackageVersion: 5.4.2
DefaultLocale: en-US
ManifestType: version
ManifestVersion: 1.10.0
