# Created with YamlCreate.ps1 v2.5.0 $debug=QUSU.CRLF.7-6-0-preview5-3.Win32NT
# yaml-language-server: $schema=https://aka.ms/winget-manifest.installer.1.10.0.schema.json

PackageIdentifier: CakeWallet.CakeWallet
PackageVersion: 5.5.0
InstallerType: inno
Scope: machine
UpgradeBehavior: install
ReleaseDate: 2025-10-15
AppsAndFeaturesEntries:
- DisplayName: Cake Wallet version 5.5.0
  Publisher: Cake Labs LLC
  ProductCode: com.cakewallet.cakewallet_is1
Installers:
- Architecture: x64
  InstallerUrl: https://github.com/cake-tech/cake_wallet/releases/download/v5.5.0/Cake_Wallet_v5.5.0_Windows.exe
  InstallerSha256: 3A53AEB3957259FCD68DF852CFF57554E8350DBE59D1C83DB8F7DA4043E4F9DD
  ProductCode: com.cakewallet.cakewallet_is1
ManifestType: installer
ManifestVersion: 1.10.0
